# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /data/db
  journal:
    enabled: true
  engine: rocksdb
#  mmapv1:
#  wiredTiger:
#  rocksdb:

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0


# systemLog:

# processManagement:

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options

#auditLog:

#snmp:
